credentials:
  usernames:
    user:
      email: takahirotefunamu@gmail.com
      name: user
      password: user
cookie:
  expiry_days: 0
  key: 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
  name: user
preauthorized:
  emails:
  - takahirotefunamu@gmail.com
